MvcLunchSite/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcLunchSite.Models
{
    public class Restaurant
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string pic { get; set; }
        public string url { get; set; }
        public ICollection<Menu> Menus { get; set; }
        public List<Restaurant> GetRestaurants()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            List<Restaurant> restaurants = new List<Restaurant>();
            foreach (Restaurant r in db.Restaurants)
                restaurants.Add(r);
            return restaurants;
        }
    }
}

MvcLunchSite/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcLunchSite.Models;
using MvcLunchSite.Helpers;
using System.Security.Principal;

namespace MvcLunchSite.Controllers
{
    public class MenuItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private SecurityHelper sh = new SecurityHelper();

        // GET: MenuItems
        public ActionResult Index()
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                var menuItems = db.MenuItems.Include(m => m.Menu);
                return View(menuItems.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MenuItems/Details/5
        public ActionResult Details(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                MenuItem menuItem = db.MenuItems.Find(id);
                if (menuItem == null)
                {
                    return HttpNotFound();
                }
                return View(menuItem);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MenuItems/Create
        public ActionResult Create()
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                ViewBag.menuID = new SelectList(db.Menus, "menuID", "menuName", RouteData.Values["id"]);
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "menuItemID,menuItemName,menuItemPrice,menuItemDescription,menuID,itemType")] MenuItem menuItem)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (ModelState.IsValid)
                {
                    db.MenuItems.Add(menuItem);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Restaurants");
                }

                ViewBag.menuID = new SelectList(db.Menus, "menuID", "menuName", menuItem.menuID);
                return View(menuItem);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MenuItems/Edit/5
        public ActionResult Edit(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                MenuItem menuItem = db.MenuItems.Find(id);
                if (menuItem == null)
                {
                    return HttpNotFound();
                }
                ViewBag.menuID = new SelectList(db.Menus, "menuID", "menuName", menuItem.menuID);
                List<string> itemList = new List<string>();
                itemList.Add("Appetizer");
                itemList.Add("Entree");
                itemList.Add("Topping");
                itemList.Add("Free");
                ViewBag.itemType = new SelectList(itemList, db.MenuItems.Where(x => x.menuItemID == id).FirstOrDefault().itemType);
                return View(menuItem);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "menuItemID,menuItemName,menuItemPrice,menuItemDescription,menuID,itemType")] MenuItem menuItem)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(menuItem).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Restaurants");
                }
                ViewBag.menuID = new SelectList(db.Menus, "menuID", "menuName", menuItem.menuID);
                return View(menuItem);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MenuItems/Delete/5
        public ActionResult Delete(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                MenuItem menuItem = db.MenuItems.Find(id);
                if (menuItem == null)
                {
                    return HttpNotFound();
                }
                return View(menuItem);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                MenuItem menuItem = db.MenuItems.Find(id);
                db.MenuItems.Remove(menuItem);
                db.SaveChanges();
                return RedirectToAction("Index", "Restaurants");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcLunchSite/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcLunchSite.Models;
using System.Data.Entity.Infrastructure;
using MvcLunchSite.Helpers;
using System.Security.Principal;

namespace MvcLunchSite.Controllers
{
    public class MenusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private SecurityHelper sh = new SecurityHelper();
        // GET: Menus
        public ActionResult Index()
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                return View(db.Menus.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu menu = db.Menus.Find(id);
                if (menu == null)
                {
                    return HttpNotFound();
                }
                return View(menu);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                ViewBag.restaurantID = new SelectList(db.Restaurants, "ID", "name", RouteData.Values["id"]);
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "menuID,restaurantID,menuName,menuNotes")] Menu menu)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (ModelState.IsValid)
                {
                    db.Menus.Add(menu);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Restaurants");
                }
                ViewBag.restaurantID = new SelectList(db.Restaurants, "ID", "name");
                return View(menu);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu menu = db.Menus.Find(id);
                if (menu == null)
                {
                    return HttpNotFound();
                }
                return View(menu);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "menuID,restaurantID,menuName,menuNotes")] Menu menu)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(menu).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Restaurants");
                }
                return View(menu);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu menu = db.Menus.Find(id);
                if (menu == null)
                {
                    return HttpNotFound();
                }
                return View(menu);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IPrincipal user = System.Web.HttpContext.Current.User;
            if (sh.atLeastAdmin(user))
            {
                Menu menu = db.Menus.Find(id);
                foreach (MenuItem item in db.MenuItems)
                {
                    if (item.menuID == id)
                    {
                        db.MenuItems.Remove(item);
                    }
                }
                db.Menus.Remove(menu);
                db.SaveChanges();
                return RedirectToAction("Index", "Restaurants");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcLunchSite/Views/Restaurants/Create.cshtml
@model MvcLunchSite.Models.Restaurant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcLunchSite/Views/Restaurants/Delete.cshtml
@model MvcLunchSite.Models.Restaurant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcLunchSite/Views/Restaurants/Details.cshtml
@model MvcLunchSite.Models.Restaurant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcLunchSite/Views/Restaurants/Edit.cshtml
@model MvcLunchSite.Models.Restaurant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcLunchSite/Views/Restaurants/Index.cshtml
@model Tuple<MvcLunchSite.Models.Restaurant,MvcLunchSite.Models.Menu,MvcLunchSite.Models.MenuItem>
@{ 
    var restaurantList = (List<MvcLunchSite.Models.Restaurant>)ViewData["RestaurantList"];
    var menuList = (List<MvcLunchSite.Models.Menu>)ViewData["MenuList"];
    var menuItemList = (List<MvcLunchSite.Models.MenuItem>)ViewData["MenuItemList"];
}
@{
    ViewBag.Title = "Restaurant";
}

<h2>Restaurants</h2>

<strong>
    @Html.ActionLink("Add Restaurant", "Create")
</strong>

@foreach (var restaurant in restaurantList)
{
    <div>
        <strong>@Html.DisplayFor(modelItem => restaurant.name)</strong>
        <strong style="float:right; text-align:right;">
            @Html.ActionLink("Edit", "Edit", new { id = restaurant.ID }) |
            @Html.ActionLink("Details", "Details", new { id = restaurant.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = restaurant.ID })
        </strong>
        <ul style="border-top: 2px solid black;">
            @foreach(var menu in menuList)
            {
                if(menu.restaurantID == restaurant.ID)
                {
                    <li>                       
                        @menu.menuName
                        <div style="float:right; text-align:right;">
                            @Html.ActionLink("Edit", "Edit", "Menus", new { id = menu.menuID }, null) |
                            @Html.ActionLink("Details", "Details", "Menus", new { id = menu.menuID }, null) |
                            @Html.ActionLink("Delete", "Delete", "Menus", new { id = menu.menuID }, null)
                        </div>
                        <ul style="border-top: 1px solid black;">
                            @foreach(var menuItem in menuItemList)
                            {
                                if(menuItem.menuID == menu.menuID) 
                                {
                                    <li style="border-bottom: 1px solid black;">
                                        @menuItem.menuItemName
                                        <div style="float:right; text-align:right;">
                                            @Html.ActionLink("Edit", "Edit", "MenuItems", new { id = menuItem.menuItemID }, null) |
                                            @Html.ActionLink("Details", "Details", "MenuItems", new { id = menuItem.menuItemID }, null) |
                                            @Html.ActionLink("Delete", "Delete", "MenuItems", new { id = menuItem.menuItemID }, null)
                                        </div>
                                    </li>
                                }
                            }
                            <li style="border-bottom: 1px solid black;">
                                @Html.ActionLink("Add Menu Item", "Create", "MenuItems", new { id = menu.menuID }, null)
                            </li>
                        </ul>
                    </li>
                }
            }
            <li style="border-bottom: 1px solid black;">
                @Html.ActionLink("Add Menu", "Create", "Menus", new { id = restaurant.ID }, null)
            </li>
        </ul>
    </div>
}


@*@foreach (var restaurant in restaurantList)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayFor(modelItem => restaurant.name)
            </th>
            <th style="text-align:right; font-weight:normal;">
                @Html.ActionLink("Edit", "Edit", new { id = restaurant.ID }) |
                @Html.ActionLink("Details", "Details", new { id = restaurant.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = restaurant.ID })
            </th>
        </tr>
    </table>

    <h2 style="margin-left:5vw;">Menus</h2>
    <p style="margin-left:5vw;">@Html.ActionLink("Create New", "Menus/Create")</p>

    foreach (var menu in menuList)
    {
        if (menu.restaurantID == restaurant.ID)
        {
            <table class="table" style="margin-left:5vw; right:5vw;">
                <tr>
                    <th>
                        @menu.menuName
                    </th>
                    <th style="text-align:right; font-weight:normal;">
                        @Html.ActionLink("Edit", "Menus/Edit", new { id = menu.menuID }) |
                        @Html.ActionLink("Details", "Menus/Details", new { id = menu.menuID }) |
                        @Html.ActionLink("Delete", "Menus/Delete", new { id = menu.menuID })
                    </th>
                </tr>
            </table>
        }
    }
}*@



@*<div>@Html.Partial("~/Views/Menus/Index.cshtml",ViewData)</div>
<div>@Html.Partial("~/Views/MenuItems/Index.cshtml",ViewData)</div>*@